name: Run tests on lambda function with cypress packages up the lambda function with the required dependencies and then deploys it to AWS with Terraform

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6

  package_lambda:
    needs: cypress-run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.3

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install boto3

      - name: Create Lambda function ZIP file
        run: |
          zip -r9 backend-aws-resume-challenge\terraform-resume\lambda_function_payload.zip backend-aws-resume-challenge/lambda_function.py



