name: Run tests on lambda function with cypress packages up the lambda function with the required dependencies and then deploys it to AWS with Terraform

on:
  push:
    branches:
      - main

jobs:
  #cypress-run:
  #  runs-on: ubuntu-22.04
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
  #    - name: Cypress run
  #      uses: cypress-io/github-action@v6

  #package-lambda:
    # needs: cypress-run
  #  runs-on: ubuntu-latest

  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v4

  #    - name: Set up python
  #      uses: actions/setup-python@v5
  #      with:
  #        python-version: 3.12.3

  #    - name: install dependencies
  #      run: |
  #        python -m pip install --upgrade pip
  #        python -m pip install boto3

  #    - name: Create Lambda function ZIP file
  #      run: |
  #        zip -r9 terraform-resume/lambda_function_payload.zip . -i lambda_function.py


  terraform-deploy:
  #  needs: cypress-run
  #  needs: package-lambda
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::767397862444:role/GitHubActions
            aws-region: us-west-2
      
      - name: Set up Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.8.3

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform changes
        run: terraform plan

      - name: Apply Terraform changes
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
