name: Deploy Lambda Function with Terraform

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.3

    - name: Install dependencies
      run: |
        python -m pip install boto3
        python -m pip install pypi-json
        pip install requests
        echo "installs complete"

    - name: Run tests
      run: python -m unittest discover -s backend-aws-resume-challenge -p 'test_.py'

    - name: tests complete
      run: echo "tests are complete"s




