name: Run tests on lambda function with cypress packages up the lambda function with the required dependencies and then deploys it to AWS with Terraform

on:
  push:
    branches:
      - main

jobs:
  #cypress-run:
  #  runs-on: ubuntu-22.04
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
  #    - name: Cypress run
  #      uses: cypress-io/github-action@v6

  #package-lambda:
    # needs: cypress-run
  #  runs-on: ubuntu-latest

  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v4

  #    - name: Set up python
  #      uses: actions/setup-python@v5
  #      with:
  #        python-version: 3.12.3

  #    - name: install dependencies
  #      run: |
  #        python -m pip install --upgrade pip
  #        python -m pip install boto3

  #    - name: Create Lambda function ZIP file
  #      run: |
  #        zip -r9 terraform-resume/lambda_function_payload.zip . -i lambda_function.py


  #terraform-deploy:
  #  needs: cypress-run
  #  needs: package-lambda
  #  runs-on: ubuntu-latest

  #  permissions:
  #    id-token: write
  #    contents: read

  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v4

  #    - name: Debug working directory contents
  #      run: ls
    
  #    - name: Configure AWS Credentials
  #      uses: aws-actions/configure-aws-credentials@v4
  #      with:
  #        role-to-assume: ${{ secrets.AWS_ROLE }}
  #        aws-region: us-west-2
      
  #    - name: Set up Terraform
  #      uses: hashicorp/setup-terraform@v2
  #      with:
  #        terraform_version: 1.8.3

  #    - name: Initialize Terraform
  #      run: terraform init
  #      working-directory: terraform-resume

  #    - name: Validate Terraform
  #      run: terraform validate
  #      working-directory: terraform-resume

  #    - name: Plan Terraform changes
  #      run: terraform plan
  #      working-directory: terraform-resume

  #    - name: Apply Terraform changes
  #      if: github.ref == 'refs/heads/main'
  #      run: terraform apply -auto-approve
  #      working-directory: terraform-resume
  
  import-terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    
    steps:  
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ secrets.AWS_ROLE }}
            aws-region: us-west-2
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.3

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform-resume

      - name: Validate Terraform
        run: terraform validate
        working-directory: terraform-resume

      - name: Import Cloudfront Distro
        run: terraform import aws_cloudfront_distribution.resume_cf_distro E2E12TP6LTG1FT
        working-directory: terraform-resume

      - name: Import Dynamodb
        run: terraform import aws_dynamodb_table.visitor_count_table visitor_count_table
        working-directory: terraform-resume

      - name: Import API Gateway
        run: terraform import aws_apigatewayv2_api.visitors_API 7vgsgyibz8
        working-directory: terraform-resume

      - name: Import Lambda
        run: terraform import aws_lambda_function.CountVisitorsFunction_lambda CountVisitorsFunction
        working-directory: terraform-resume

      - name: Import IAM Role for Lambda
        run: terraform import aws_iam_role.iam_for_lambda CountVisitorsFunction-role-ovlfetzh
        working-directory: terraform-resume
        
        